
//scss區塊
import '../styles/all.scss'; 
import './_btn.scss';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import './globals.scss';
//scss區塊

// js區塊
// 暫時不引入
// import BootstrapClient from './bootstrap-client';
// js區塊

//元件區
import Header from '@/components/common/Header/Header';
import Footer from '@/components/common/Footer/Footer';
import Providers from '@/providers/roviders';
import ModalRoot from '@/components/common/ModalRoot/ModalRoot';
import NavSpace from '@/components/common/navSpace/NavSpace';
//元件區


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Material Symbols（Outlined 範例） */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
        />
      </head>
      <body>
        {/* js載入 */}
        {/* 暫時不引入 */}
        {/* <BootstrapClient /> */}
        {/* js載入 */}
        <Providers>
          <Header />
          <NavSpace />
          {children}
          <Footer />
          <ModalRoot />
        </Providers>
      </body>
    </html>
  );
}
